Repository toltec-dev/toltec, pull requests merged in 2020-09, with the labels that each got.

#1 Add rust toolchain and retris package
  image/Dockerfile
  image/README.md
  package/retris/package
Labels: new package

#29 [WIP] Update oxide to 1.3.3-beta
  package/oxide/package
Labels: packages

#44 package: add koreader 2020.08.01
  package/koreader/koreader
  package/koreader/koreader.draft
  package/koreader/package
Labels: packages

#63 Make launchers installable alongside each other
  package/draft/draft.service
  package/draft/package
  package/oxide/package
  package/oxide/tarnish.service
  package/remux/package
  package/remux/remux.service
  package/xochitl/package
  package/xochitl/xochitl.draft
  package/xochitl/xochitl.png
Labels: packages

#71 Allow disabling the build() step
  package/koreader/package
  package/xochitl/package
  scripts/lib
  scripts/package-build
Labels: tooling

#65 Move maintainer scripts definition to recipe file
  docs/package.md
  package/draft/package
  package/draft/postinst
  package/draft/postrm
  package/draft/prerm
  package/oxide/package
  package/oxide/postinst
  package/oxide/postrm
  package/oxide/prerm
  package/plato/package
  package/plato/postinst
  package/plato/postrm
  package/remux/package
  package/remux/postinst
  package/remux/postrm
  package/remux/prerm
  scripts/install-lib
  scripts/package-build
  scripts/package-lib
  scripts/repo-build
  scripts/repo-check
Labels: tooling

#80 Add draft configuration for calculator
  package/calculator/calculator.draft
  package/calculator/calculator.svg
  package/calculator/package
Labels: packages

#86 Handle recipe metadata fields more safely
  docs/package.md
  package/harmony/package
  package/mines/package
  package/nao/package
  package/remarkable-splash/package
  package/rmservewacominput/package
  package/simple/package
  scripts/package-build
  scripts/package-lib
  scripts/repo-build
Labels: tooling

#87 Update koreader to v2020.09.29-1
  package/koreader/package
Labels: packages

#89 Update remux to latest (2020.09.29)
  package/remux/package
Labels: packages
