Repository toltec-dev/toltec, pull requests merged in 2020-10, with the labels that each got.

#90 Add recrossable
  package/recrossable/package
  package/recrossable/recrossable.draft
  package/recrossable/recrossable.svg
  package/recrossable/synthesize-pen-events.patch
Labels: packages

#93 Reuse local repo artifacts in repo-build
  Makefile
  scripts/package-build
  scripts/package-lib
  scripts/repo-build
Labels: tooling

#94 Use the updated syntax for repo-build in workflows
  .github/workflows/stable.yml
  .github/workflows/testing.yml
Labels: bug, tooling

#88 Add web build scripts
  package/appmarkable/package
  package/harmony/package
  package/mines/package
  package/nao/package
  package/remux/package
  package/simple/package
  scripts/repo-build
  scripts/repo-build-web
Labels: documentation, tooling

#96 Add and enforce a style guide
  .editorconfig
  .github/workflows/pr.yml
  Makefile
  README.md
  docs/building.md
  docs/contribute.md
  docs/contributing.md
  docs/package.md
  package/.shellcheckrc
  package/appmarkable/package
  package/calculator/package
  package/draft/package
  package/fingerterm/package
  package/harmony/package
  package/koreader/package
  package/mines/package
  package/nao/package
  package/oxide/package
  package/plato/package
  package/recrossable/package
  package/remarkable-splash/package
  package/remux/package
  package/retris/package
  package/rmservewacominput/package
  package/simple/package
  package/xochitl/package
  scripts/install-lib
  scripts/package-build
  scripts/package-lib
  scripts/repo-build
  scripts/repo-build-web
Labels: documentation, tooling

#97 Add chessmarkable 0.3.3-1
  package/chessmarkable/package
Labels: packages

#101 Make the package listings sortable
  scripts/repo-build-web
Labels: tooling

#110 README: Fix typo in install instructions
  README.md
Labels: bug, documentation

#113 recrossable: Update and remove patch
  package/recrossable/package
  package/recrossable/synthesize-pen-events.patch
Labels: packages

#112 update remux, harmony to newest version. rename minesweeper -> mines
  package/harmony/package
  package/mines/package
  package/remux/package
Labels: packages

#114 License the project under MIT
  LICENSE
  Makefile
  docs/contributing.md
  package/appmarkable/package
  package/calculator/calculator.draft
  package/calculator/calculator.svg
  package/calculator/package
  package/chessmarkable/package
  package/draft/draft.service
  package/draft/package
  package/fingerterm/fingerterm.draft
  package/fingerterm/package
  package/harmony/package
  package/koreader/koreader
  package/koreader/koreader.draft
  package/koreader/package
  package/mines/package
  package/nao/package
  package/oxide/package
  package/plato/package
  package/recrossable/package
  package/recrossable/recrossable.draft
  package/recrossable/recrossable.svg
  package/remarkable-splash/package
  package/remux/package
  package/remux/remux.service
  package/retris/package
  package/rmservewacominput/package
  package/simple/package
  package/xochitl/package
  package/xochitl/xochitl.draft
  scripts/install-lib
  scripts/package-build
  scripts/package-lib
  scripts/repo-build
  scripts/repo-build-web
  scripts/repo-check
Labels: documentation

#111 [whiteboard][0.3.0] - New Package
  package/whiteboard-hypercard/package
  package/whiteboard-hypercard/whiteboard-hypercard.draft
Labels: packages

#116 Improve source archive extraction
  docs/package.md
  package/oxide/package
  scripts/package-build
  scripts/package-lib
Labels: tooling

#38 Add bootstrap script
  .github/workflows/stable.yml
  Makefile
  README.md
  scripts/bootstrap/bootstrap
  scripts/bootstrap/checksum-check
Labels: documentation

#118 Fix KOReader build
  package/koreader/package
  scripts/package-lib
Labels: packages

#108 Update chessmarkable to 0.4.2-1
  package/chessmarkable/package
Labels: packages

#119 Add reboot-guard
  package/reboot-guard/package
  package/reboot-guard/rguard.patch
  package/reboot-guard/rguard.service
Labels: packages

#121 Fix handling packages with multiple dependencies
  package/reboot-guard/package
  scripts/package-build
  scripts/package-lib
Labels: bug, tooling

#122 Fix reboot-guard dependency
  package/reboot-guard/package
Labels: bug, packages

#124 Configure Opkg to fetch Entware packages using TLS
  README.md
  scripts/bootstrap/bootstrap
Labels: bug

#123 Stable merge window for week 42 of 2020
  .github/workflows/stable.yml
  LICENSE
  Makefile
  README.md
  docs/contributing.md
  docs/package.md
  package/appmarkable/package
  package/calculator/calculator.draft
  package/calculator/calculator.svg
  package/calculator/package
  package/chessmarkable/package
  package/draft/draft.service
  package/draft/package
  package/fingerterm/fingerterm.draft
  package/fingerterm/package
  package/harmony/package
  package/nao/package
  package/oxide/package
  package/plato/package
  package/recrossable/package
  package/recrossable/recrossable.draft
  package/recrossable/recrossable.svg
  package/recrossable/synthesize-pen-events.patch
  package/remarkable-splash/package
  package/remux/package
  package/remux/remux.service
  package/retris/package
  package/rmservewacominput/package
  package/simple/package
  package/whiteboard-hypercard/package
  package/whiteboard-hypercard/whiteboard-hypercard.draft
  package/xochitl/package
  package/xochitl/xochitl.draft
  scripts/bootstrap/bootstrap
  scripts/bootstrap/checksum-check
  scripts/install-lib
  scripts/package-build
  scripts/package-lib
  scripts/repo-build
  scripts/repo-build-web
  scripts/repo-check
Labels: merge

#125 Update KOReader to version 2020.10
  package/koreader/package
Labels: packages

#81 Implement the process for moving packages from testing to stable
  README.md
  docs/branches.md
  docs/channels.md
  docs/package.md
Labels: documentation, merge

#126 package: update remux to latest
  package/remux/package
Labels: packages

#127 Improve package docs and fix #120
  docs/package.md
  scripts/package-build
Labels: documentation, tooling

#131 Implement split packages
  .github/workflows/stable.yml
  .github/workflows/testing.yml
  Makefile
  docs/package.md
  package/appmarkable/package
  package/calculator/package
  package/chessmarkable/package
  package/draft/package
  package/fingerterm/package
  package/harmony/package
  package/koreader/package
  package/mines/package
  package/nao/package
  package/oxide/package
  package/plato/package
  package/reboot-guard/package
  package/recrossable/package
  package/remarkable-splash/package
  package/remux/package
  package/retris/package
  package/rmkit/package
  package/rmkit/remux.service
  package/rmservewacominput/package
  package/simple/package
  package/whiteboard-hypercard/package
  package/xochitl/package
  scripts/package-build
  scripts/package-lib
  scripts/repo-build
  scripts/repo-build-web
Labels: packages, tooling

#135 Add VNSee 0.3.0
  docs/package.md
  package/vnsee/package
  scripts/package-build
  scripts/package-lib
Labels: packages, tooling
