Repository toltec-dev/toltec, pull requests merged in 2021-07, with the labels that each got.

#361 [innernet] Update to v1.3.1
  package/innernet/package
Labels: packages

#366 Update packages for release 2.6 and onwards
  package/appmarkable/package
  package/bash-completion/package
  package/calculator/package
  package/chessmarkable/package
  package/display/package
  package/draft/package
  package/evtest/package
  package/fbink/package
  package/fingerterm/package
  package/fuse/fix-multiple-yylloc-definitions.patch
  package/fuse/package
  package/gocryptfs/package
  package/innernet/package
  package/keywriter/package
  package/libdlib/package
  package/libvncserver/package
  package/oxide/package
  package/oxide/support-2.6.patch
  package/plato/package
  package/puzzles/package
  package/quickjs/package
  package/recrossable/package
  package/remarkable-splash/package
  package/restream/package
  package/retris/package
  package/rmkit/package
  package/rmservewacominput/package
  package/templatectl/package
  package/toltec-completion/package
  package/vnsee/package
  package/wikipedia/package
  package/wireguard/fix-multiple-yylloc-definitions.patch
  package/wireguard/package
  package/yaft/package
  package/zoneinfo-utils/package
  package/zshelf/package
Labels: packages

#383 Create remarkable-stylus package
  package/display/package
  package/display/rm2fb-preload.env
  package/remarkable-stylus/package
  package/remarkable-stylus/remarkable-stylus.env
  package/xochitl/env-readme
  package/xochitl/package
  package/xochitl/xochitl
Labels: packages

#385 Update ddvk-hacks to latest
  package/ddvk-hacks/package
Labels: packages

#382 Update to Oxide v2.2
  package/oxide/package
  package/oxide/support-2.6.patch
  package/xochitl/package
  package/xochitl/xochitl.oxide
Labels: packages

#386 Fix xochtil chroot launching
  package/xochitl/package
  package/xochitl/xochitl.oxide
Labels: bug, packages

#379 Manage Opkg configuration with toltecctl
  Makefile
  README.md
  docs/branches.md
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
  package/toltec-completion/_toltecctl
  package/toltec-completion/package
  scripts/bootstrap/bootstrap
Labels: documentation, install, packages

#389 Update KOReader to v2021.07
  package/koreader/package
Labels: packages

#396 yaft & tilem: Add missing dependency on display
  package/tilem/package
  package/yaft/package
Labels: packages

#394 puzzles: Fix missing save dir
  package/puzzles/package
Labels: bug, packages

#395 netsurf: Improve rM2 compatibility
  package/netsurf/package
Labels: packages

#397 remux: Fix xochitl start issue
  package/rmkit/package
  package/rmkit/patch-remux-start-xochitl.diff
Labels: bug, packages

#387 Update fbink to 1.23.2
  package/fbink/package
Labels: packages

#392 Update chessmarkable to 0.8.0-1
  package/chessmarkable/package
Labels: packages

#388 Update Oxide to v2.2.1
  package/oxide/package
Labels: packages

#398 Declare rM2 as supported in the README
  README.md
Labels: documentation

#400 Update micro to 2.0.9
  package/micro/package
Labels: packages

#384 Update innernet to 1.4.0
  package/innernet/package
Labels: packages

#402 Improve Opkg completion
  package/toltec-completion/_opkg
Labels: packages

#403 Bump toltec-completion version number to 0.3.0-1
  package/toltec-completion/package
Labels: packages

#405 fuse: Fix on-demand loading after install on rM1
  package/fuse/package
Labels: packages
