Repository toltec-dev/toltec, pull requests merged in 2021-04, with the labels that each got.

#325 Use xochitl instead of remarkable-shutdown in rm2fb-server
  package/rm2fb/overwrite-server-argv0.patch
  package/rm2fb/package
  package/rm2fb/rm2fb-server
  package/rm2fb/rm2fb.service
Labels: packages

#310 Implement architecture separation
  .mypy.ini
  Makefile
  README.md
  docs/package.md
  package/appmarkable/package
  package/calculator/package
  package/chessmarkable/package
  package/display/overwrite-server-argv0.patch
  package/display/package
  package/display/rm2fb-client
  package/display/rm2fb.service
  package/dotnet/package
  package/draft/package
  package/fingerterm/package
  package/keywriter/package
  package/koreader/koreader
  package/koreader/package
  package/oxide/package
  package/plato/package
  package/quickjs/package
  package/reboot-guard/package
  package/recrossable/package
  package/remarkable-splash/package
  package/retris/package
  package/rm2-suspend-fix/package
  package/rm2fb/package
  package/rm2fb/rm2fb-client
  package/rm2fb/rm2fb-server
  package/rm2fb/rm2fb.conf
  package/rmkit/2021_03_05_genie.diff
  package/rmkit/package
  package/rmkit/patch-remux-duplicate-xochitl.diff
  package/rmservewacominput/package
  package/template-cartesian-graph/package
  package/toltec-bootstrap/package
  package/vnsee/package
  package/whiteboard-hypercard/package
  package/wikipedia/package
  package/wireguard/package
  package/xochitl/package
  package/xochitl/toltec-wrapper.conf
  package/xochitl/xochitl
  package/xochitl/xochitl.draft
  package/xochitl/xochitl.oxide
  package/zoneinfo-utils/package
  package/zshelf/package
  requirements.txt
  scripts/bootstrap/bootstrap
  scripts/package_build.py
  scripts/repo_build.py
  scripts/toltec/builder.py
  scripts/toltec/recipe.py
  scripts/toltec/repo.py
  scripts/toltec/templates/listing.html
  scripts/toltec/util.py
Labels: install, packages, tooling

#329 Fix partial repository builds
  scripts/toltec/repo.py
Labels: bug, tooling

#336 Use the Bash binary in PATH for parsing recipes
  scripts/toltec/bash.py
Labels: tooling

#261 [Yaft][0.0.4] - New Package
  package/yaft/package
Labels: packages

#303 Move zoneinfo bind mount to zoneinfo-utils package
  README.md
  package/templatectl/package
  package/templatectl/usr-share-remarkable-templates.mount
  package/toltec-bootstrap/entware-reenable
  package/toltec-bootstrap/package
  package/zoneinfo-utils/package
  scripts/bootstrap/bootstrap
  scripts/install-lib
Labels: install, packages
