Repository toltec-dev/toltec, pull requests merged in 2021-09, with the labels that each got.

#423 bootstrap: Fix TLS, check if .entware exists, and improve error messages
  README.md
  scripts/bootstrap/bootstrap
Labels: bug, install

#436 Update KOReader to v2021.09
  package/koreader/package
Labels: packages

#284 Add first draft for pr templates
  .github/pull_request_template.md
Labels: documentation

#441 koreader: Add service unit
  package/koreader/koreader-toltec.service
  package/koreader/package
  package/xochitl/package
  package/xochitl/toltec-wrapper.conf
  scripts/install-lib
Labels: packages

#439 Update ddvk-hacks to 24.04 (support for 2.9)
  package/ddvk-hacks/package
Labels: packages

#444 Update Oxide to v2.2.2
  package/oxide/package
Labels: packages
