Repository toltec-dev/toltec, pull requests merged in 2021-12, with the labels that each got.

#505 Update xochitl.oxide to support templatectl
  package/xochitl/package
  package/xochitl/xochitl.oxide
Labels: packages

#507 Merge/2021 w48
  package/rmkit/package
Labels: merge

#448 Create rmfakecloud-proxy package
  package/rmfakecloud-proxy/package
  package/rmfakecloud-proxy/rmfakecloud-proxy.service
  package/rmfakecloud-proxy/rmfakecloudctl
Labels: packages

#510 Add hint for when the temporary wget or opkg files exist
  package/toltec-bootstrap/package
  scripts/bootstrap/bootstrap
Labels: packages

#513 rmfakecloud-proxy:  Add status subcommand
  package/rmfakecloud-proxy/package
  package/rmfakecloud-proxy/rmfakecloudctl
Labels: bug, packages

#516 Stable merge for week 51 of 2021
  package/display/package
  package/toltec-bootstrap/package
  scripts/bootstrap/bootstrap
Labels: merge

#517 Update KOReader to v2021.12
  package/koreader/package
Labels: packages

#514 Update ddvk-hacks to 29.01-1
  package/ddvk-hacks/package
Labels: packages

#518 Update KOReader to 2021.12.1
  package/koreader/package
Labels: packages

#530 Force rm2fb-client to depend on a specific version of display
  package/display/package
  scripts/toltec/version.py
Labels: packages

#492 Package netevent
  package/netevent/package
Labels: packages

#531 display: Release 0.0.13
  package/display/package
  package/display/rm2fb.service
Labels: packages
