Repository toltec-dev/toltec, pull requests merged in 2021-01, with the labels that each got.

#187 Use systemctl is-enabled in function is-enabled
  README.md
  package/rm2fb/package
  scripts/bootstrap/bootstrap
  scripts/install-lib
Labels: tooling

#189 Prevent unwanted PRs against stable
  .github/workflows/pr-labels.yml
  docs/contributing.md
Labels: documentation, tooling

#192 Launch the PR label checker on more events
  .github/workflows/pr-labels.yml
Labels: tooling

#198 Fix base image for stripping not found
  scripts/package-build
Labels: tooling

#195 Add keywriter package
  package/keywriter/keywriter.draft
  package/keywriter/package
Labels: packages

#200 Default image if missing
  scripts/package-build
Labels: tooling

#183 Add rm2-suspend-fix
  package/rm2-suspend-fix/package
  package/rm2-suspend-fix/rm2-suspend-fix.sh
Labels: packages

#205 Backport KOReader support for reMarkable 2
  package/koreader/package
  package/koreader/rm2-support.patch
Labels: packages

#208 [issue->pr] how-to-enable says to disable shutdown.target
  package/draft/package
  package/oxide/package
  package/rmkit/package
  scripts/install-lib
Labels: bug

#67 Remove old package versions
  .github/workflows/stable.yml
  .github/workflows/testing.yml
Labels: tooling

#215 [build] only build new artifacts during PRs should work for stable too
  .github/workflows/pr.yml
Labels: tooling

#199 Oxide v2.1
  package/calculator/package
  package/koreader/KOReader.oxide
  package/koreader/koreader.draft
  package/koreader/package
  package/oxide/package
  package/rmkit/package
  package/xochitl/package
  package/xochitl/xochitl.oxide
  scripts/install-lib
  scripts/package-build
  scripts/package-lib
Labels: packages

#217 restream: Fix wrong hook name (postinstall → configure)
  package/restream/package
Labels: bug

#204 Stable merge window for week 02 of 2021
  .github/workflows/pr-labels.yml
  docs/contributing.md
  package/appmarkable/package
  package/calculator/package
  package/chessmarkable/package
  package/dotnet/package
  package/draft/package
  package/evtest/package
  package/fbink/package
  package/fingerterm/package
  package/keywriter/keywriter.draft
  package/keywriter/package
  package/koreader/package
  package/koreader/rm2-support.patch
  package/micro/package
  package/oxide/package
  package/plato/package
  package/reboot-guard/package
  package/recrossable/package
  package/remarkable-splash/package
  package/restream/package
  package/retris/package
  package/rm2-suspend-fix/package
  package/rm2-suspend-fix/rm2-suspend-fix.sh
  package/rm2fb/package
  package/rmkit/genie.service
  package/rmkit/package
  package/rmservewacominput/package
  package/toltec-bootstrap/package
  package/vnsee/package
  package/whiteboard-hypercard/package
  package/xochitl/package
  scripts/install-lib
  scripts/package-build
Labels: merge

#225 Workflow scripts improvements
  .github/actions/discord-send/action.yml
  .github/actions/setup/action.yml
  .github/actions/sync-repository/action.yml
  .github/workflows/pr-labels.yml
  .github/workflows/pr.yml
  .github/workflows/stable.yml
  .github/workflows/testing.yml
Labels: tooling

#229 Link to org-wide security policy and code of conduct
  docs/code_of_conduct.md
  docs/contributing.md
  docs/security.md
Labels: documentation

#230 Update bootstrap wget to 1.21.1
  README.md
  package/toltec-bootstrap/package
  scripts/bootstrap/bootstrap
Labels: install

#213 Add timezone mount to bootstrap
  README.md
  package/toltec-bootstrap/entware-reenable
  package/toltec-bootstrap/package
  scripts/bootstrap/bootstrap
Labels: install

#226 Document new sections & move packages to new sections
  docs/package.md
  package/appmarkable/package
  package/calculator/package
  package/chessmarkable/package
  package/dotnet/package
  package/draft/package
  package/evtest/package
  package/fbink/package
  package/fingerterm/package
  package/keywriter/package
  package/koreader/package
  package/micro/package
  package/oxide/package
  package/plato/package
  package/reboot-guard/package
  package/recrossable/package
  package/remarkable-splash/package
  package/restream/package
  package/retris/package
  package/rm2-suspend-fix/package
  package/rm2fb/package
  package/rmkit/package
  package/rmservewacominput/package
  package/toltec-bootstrap/package
  package/vnsee/package
  package/whiteboard-hypercard/package
  package/xochitl/package
Labels: documentation, packages

#182 Create zoneinfo-utils package
  package/zoneinfo-utils/package
  scripts/package-build
Labels: packages

#76 Update packaging documentation
  docs/REFERENCE.md
  docs/branches.md
  docs/building.md
  docs/contributing.md
  docs/opkg.md
  docs/package-guide.md
  docs/package.md
Labels: documentation

#222 templatectl: Add/Remove items from templates.json via cli
  package/draft/package
  package/oxide/package
  package/reboot-guard/package
  package/rmkit/package
  package/template-cartesian-graph/package
  package/templatectl/package
  package/templatectl/usr-share-remarkable-templates.mount
  scripts/package-build
Labels: packages

#245 [web] change fonts on webpage
  scripts/repo-build-web
Labels: web

#244 Update fingerterm
  package/fingerterm/package
Labels: packages

#249 Fix link in docs/package.md
  docs/package.md
Labels: documentation

#181 [wireguard][1.0.20201221] - New Package
  package/wireguard/package
Labels: packages

#193 [docs] webpage built from rst
  .github/actions/setup/action.yml
  .github/workflows/stable.yml
  Makefile
  scripts/web-build
  web/docutils.conf
  web/index.rst
  web/logo.png
  web/nao.png
  web/toltec.css
Labels: web

#256 Fix missing prerm script in rm2fb
  package/rm2fb/package
Labels: bug, packages

#232 Stable merge window for week 03 of 2020
  .github/actions/discord-send/action.yml
  .github/actions/setup/action.yml
  .github/actions/sync-repository/action.yml
  .github/workflows/pr-labels.yml
  .github/workflows/pr.yml
  .github/workflows/stable.yml
  .github/workflows/testing.yml
  Makefile
  README.md
  docs/code_of_conduct.md
  docs/contributing.md
  docs/security.md
  package/calculator/package
  package/draft/package
  package/koreader/KOReader.oxide
  package/koreader/koreader.draft
  package/koreader/package
  package/oxide/package
  package/plato/package
  package/rmkit/genie.service
  package/rmkit/package
  package/toltec-bootstrap/package
  package/xochitl/package
  package/xochitl/xochitl.oxide
  scripts/bootstrap/bootstrap
  scripts/install-lib
  scripts/package-build
  scripts/package-lib
  scripts/repo-build
  scripts/repo-build-web
Labels: merge

#218 Rewrite repo-build and package-build in Python
  .github/actions/setup/action.yml
  .github/workflows/pr.yml
  .github/workflows/stable.yml
  .github/workflows/testing.yml
  .mypy.ini
  .pylintrc
  Makefile
  docs/building.md
  docs/contributing.md
  docs/package.md
  package/koreader/package
  package/zoneinfo-utils/package
  requirements.txt
  scripts/opkg/arfile.py
  scripts/opkg/opkg-make-index
  scripts/opkg/opkg.py
  scripts/package-build
  scripts/package_build.py
  scripts/repo-build
  scripts/repo_build.py
  scripts/toltec/__init__.py
  scripts/toltec/bash.py
  scripts/toltec/builder.py
  scripts/toltec/ipk.py
  scripts/toltec/paths.py
  scripts/toltec/recipe.py
  scripts/toltec/repo.py
  scripts/toltec/util.py
  scripts/toltec/version.py
Labels: tooling

#262 Hardcode REMOTE_HTTP secret in PR workflows
  .github/workflows/pr.yml
Labels: bug, tooling

#263 Print msgs on error
  scripts/toltec/bash.py
  scripts/toltec/builder.py
Labels: tooling

#267 Upgrade VNSee to 0.3.1
  package/vnsee/package
Labels: packages

#266 Rewrite repo-build-web in Python
  .github/workflows/stable.yml
  .github/workflows/testing.yml
  requirements.txt
  scripts/repo-build-web
  scripts/repo_build.py
  scripts/toltec/repo.py
  scripts/toltec/templates/listing.html
  scripts/toltec/templating.py
Labels: tooling
