Repository toltec-dev/toltec, pull requests merged in 2021-06, with the labels that each got.

#355 Update VNSee to 0.4.0 and add launcher files
  package/vnsee/VNSee.oxide
  package/vnsee/package
  package/vnsee/vnsee-gui-set-path.patch
  package/vnsee/vnsee.draft
  package/vnsee/vnsee.png
Labels: packages

#277 Add bash-completion and toltec-completion packages
  package/bash-completion/package
  package/toltec-completion/_opkg
  package/toltec-completion/_toltecctl
  package/toltec-completion/package
Labels: packages

#356 Add uninstall script and make the bootstrap script install-only
  README.md
  package/toltec-bootstrap/entware-reenable
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
  package/toltec-completion/_toltecctl
  package/toltec-completion/package
  scripts/bootstrap/bootstrap
  scripts/package-lib
Labels: install, packages

#363 Update rm2fb to v0.0.4
  package/display/overwrite-server-argv0.patch
  package/display/package
Labels: packages

#365 toltecctl: Fix typo in uninstall function
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
Labels: packages

#371 display: Add support for release 2.8
  package/display/package
Labels: packages

#369 Hotfix: Fix local wget download issue in stable
  README.md
  package/toltec-bootstrap/package
  scripts/bootstrap/bootstrap
Labels: bug, install, merge

#372 Fix toltecctl set-path command if .bashrc does not exist
  README.md
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
  scripts/bootstrap/bootstrap
Labels: bug, install, packages

#342 Update the bootstrap script to install wget-ssl
  README.md
  package/toltec-bootstrap/package
  scripts/bootstrap/bootstrap
Labels: install

#378 Update KOReader to v2021.06
  package/koreader/package
Labels: packages

#339 [netsurf] Add netsurf package
  package/netsurf/netsurf.draft
  package/netsurf/package
Labels: packages
