Repository toltec-dev/toltec, pull requests merged in 2021-11, with the labels that each got.

#487 Update rm2fb to v0.0.9
  package/display/package
Labels: packages

#485 Update doomarkable to 0.4.1
  package/doomarkable/package
Labels: packages

#494 Updating ddvk-hacks to latest
  package/ddvk-hacks/package
Labels: packages

#493 Update rm2fb to v0.0.10
  package/display/package
Labels: packages

#496 Update KOReader to v2021.11
  package/koreader/package
Labels: packages

#477 Stable merge for week 42 of 2021
  .github/actions/setup/action.yml
  package/koreader/package
  package/rmkit/package
  package/rmkit/patch-remux-duplicate-xochitl.diff
  package/rmkit/patch-remux-start-xochitl.diff
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
Labels: merge

#499 Fix bootstrap script dep error during toltec-bootstrap install
  README.md
  package/toltec-bootstrap/package
  scripts/bootstrap/bootstrap
Labels: bug, install

#500 Hotfix: Fix bootstrap script failing in stable
  README.md
  package/toltec-bootstrap/package
  scripts/bootstrap/bootstrap
Labels: bug, merge

#498 Move installation and usage instructions to the website
  Makefile
  README.md
  scripts/bootstrap/checksum-check
Labels: documentation

#497 Stable merge for week 46 of 2021
  .github/pull_request_template.md
  package/display/package
  package/doomarkable/package
  package/dotnet/package
  package/mmc-utils/0001-Makefile-Remove-Werror.patch
  package/mmc-utils/package
  package/vnsee/package
  package/whiteboard-hypercard/package
Labels: merge

#502 Stable merge for week 47 of 2021
  Makefile
  README.md
  package/ddvk-hacks/package
  package/display/package
  package/doomarkable/package
  package/innernet/package
  package/koreader/package
  package/rmkit/package
  package/rmkit/remux.service
  package/xochitl/package
  package/xochitl/xochitl.oxide
  scripts/bootstrap/checksum-check
Labels: merge
