Repository toltec-dev/toltec, pull requests merged in 2021-08, with the labels that each got.

#408 Update micro to 2.0.10
  package/micro/package
Labels: packages

#410 display: Update to release v0.0.6
  package/display/package
  scripts/toltec/recipe.py
Labels: packages

#412 scripts/toltec/bash.py: Disable security_ops
  scripts/toltec/bash.py
Labels: tooling

#417 display: Update to release v0.0.7
  package/display/package
Labels: packages

#411 Stable merge for week 32 of 2021
  package/display/package
  package/innernet/package
  package/micro/package
  package/toltec-completion/_opkg
  package/toltec-completion/package
  scripts/toltec/recipe.py
Labels: merge

#425 Update fbink to v1.24.0
  package/fbink/package
Labels: packages
