Repository toltec-dev/toltec, pull requests merged in 2022-02, with the labels that each got.

#545 Update innernet to 1.5.3
  package/innernet/build.patch
  package/innernet/package
Labels: packages

#552 Update rm2fb to v0.0.14
  package/display/package
Labels: packages

#557 Fix link formatting in Readme and Docs
  README.md
  docs/code_of_conduct.md
  docs/security.md
Labels: documentation

#560 Hotfixes for stable merge of week 6
  package/innernet/package
  package/plato/package
  package/rmkit/package
Labels: bug, packages

#556 Stable merge for week 6 of 2022
  .gitignore
  package/display/package
  package/folly/folly.draft
  package/folly/package
  package/innernet/build.patch
  package/innernet/package
  package/koreader/package
  package/plato/package
  package/rmkit/changelog
  package/rmkit/package
  package/toltec-completion/_opkg
  package/toltec-completion/package
  scripts/toltec/builder.py
Labels: merge

#563 Stable merge for week 7 of 2022
  README.md
  docs/code_of_conduct.md
  docs/security.md
  package/ddvk-hacks/package
Labels: merge

#564 folly: Remove hardcoded paths and values in recipe
  package/folly/package
Labels: packages
