Repository toltec-dev/toltec, pull requests merged in 2023-12, with the labels that each got.

#758 Update display/rm2fb-client to v0.0.32
  package/display/package
Labels: packages

#773 Move release information to environment variables
  .github/workflows/stable.yml
Labels: bug, tooling

#774 Fix release announcements
  .github/workflows/stable.yml
Labels: merge

#775 Hub fix
  .github/workflows/stable.yml
Labels: bug, tooling

#776 Emergency Fix for missing release
  .github/workflows/stable.yml
Labels: merge

#769 Update neofetch to v1.1.0
  package/neofetch/package
Labels: packages

#768 Update webinterface-wifi to v2.0.0
  package/webinterface-wifi/package
  package/webinterface-wifi/webinterface-wifi-toltec.service
Labels: packages

#770 Add package webinterface-onboot v1.2.2
  package/webinterface-onboot/package
  package/webinterface-onboot/webinterface-onboot-toltec.service
Labels: packages

#720 Force ddvk-hacks to be reinstalled on upgrade
  package/ddvk-hacks/package
Labels: bug, packages

#771 Add package: webinterface-upload-button v1.0.1
  package/webinterface-upload-button/package
Labels: packages

#772 Add package: signature-rm v1.0.2
  package/signature-rm/package
  package/webinterface-onboot/package
Labels: packages

#721 Clean up systemd unit disable logic
  package/display/package
  package/draft/package
  package/koreader/package
  package/oxide/package
  package/reboot-guard/package
  package/rmfakecloud-proxy/package
  package/rmkit/package
  package/tailscale-systemd/package
  package/toltec-base/package
  package/webinterface-onboot/package
  package/webinterface-wifi/package
  package/xochitl/package
  scripts/install-lib
Labels: packages, tooling

#784 Remove wireguard-tools from wireguard
  package/wireguard-tools/package
  package/wireguard/package
Labels: packages

#804 Add package: bottom
  package/bottom/package
Labels: packages

#802 Update lf to r31
  package/lf/package
Labels: packages

#801 Update ripgrep to 14.0.3
  package/ripgrep/package
Labels: packages

#782 Stable merge window for week 49 of 2023
  docs/package.md
  package/ddvk-hacks/package
  package/display/package
  package/draft/package
  package/koreader/package
  package/linux-stracciatella/package
  package/micro/package
  package/neofetch/package
  package/oxide/package
  package/reboot-guard/package
  package/rmfakecloud-proxy/package
  package/rmfm/package
  package/rmkit/package
  package/signature-rm/package
  package/tailscale-systemd/package
  package/toltec-base/package
  package/webinterface-onboot/package
  package/webinterface-onboot/webinterface-onboot-toltec.service
  package/webinterface-upload-button/package
  package/webinterface-wifi/package
  package/webinterface-wifi/webinterface-wifi-toltec.service
  package/wireguard/package
  package/xochitl/package
  scripts/install-lib
  scripts/toltec/recipe.py
Labels: merge

#790 Update webinterface-upload-button to 1.1.1
  package/webinterface-upload-button/package
Labels: packages

#811 lf: Fix missing dependency error
  package/lf/package
Labels: packages
