Repository toltec-dev/toltec, pull requests merged in 2023-08, with the labels that each got.

#684 Update to python 3.10
  .github/actions/setup/action.yml
  .github/workflows/pr.yml
  .github/workflows/stable.yml
  .github/workflows/testing.yml
  docs/building.md
  requirements.txt
  scripts/toltec/bash.py
  scripts/toltec/builder.py
  scripts/toltec/graphlib.py
  scripts/toltec/ipk.py
  scripts/toltec/recipe.py
  scripts/toltec/repo.py
  scripts/toltec/version.py
Labels: tooling

#716 Update yaft to 0.0.8
  package/yaft/package
Labels: packages

#719 Add sill package
  package/sill/package
  package/sill/sill.draft
Labels: packages

#715 Add terminfo dependency to yaft and add /opt/etc/profile to /etc/prof…
  package/toltec-base/package
  package/yaft/bash-l.patch
  package/yaft/package
Labels: packages

#571 rMscreens
  package/rmscreens/package
Labels: packages

#657 package/linux-mainline: Bump to 6.2
  package/linux-mainline/package
Labels: packages

#711 Add issue templates
  .github/ISSUE_TEMPLATE/documentation-issue.md
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/installation-issue.md
  .github/ISSUE_TEMPLATE/package-issue.md
  .github/ISSUE_TEMPLATE/package-request.md
Labels: documentation

#722 Stable merge for Week 33 of 2023
  .github/ISSUE_TEMPLATE/documentation-issue.md
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/installation-issue.md
  .github/ISSUE_TEMPLATE/package-issue.md
  .github/ISSUE_TEMPLATE/package-request.md
  .github/actions/setup/action.yml
  .github/workflows/pr.yml
  .github/workflows/stable.yml
  .github/workflows/testing.yml
  docs/building.md
  package/linux-mainline/package
  package/reterm/package
  package/rmscreens/package
  package/sill/package
  package/sill/sill.draft
  package/toltec-base/package
  package/yaft/bash-l.patch
  package/yaft/package
  requirements.txt
  scripts/toltec/bash.py
  scripts/toltec/builder.py
  scripts/toltec/graphlib.py
  scripts/toltec/ipk.py
  scripts/toltec/recipe.py
  scripts/toltec/repo.py
  scripts/toltec/version.py
Labels: merge

#698 Update oxide to v2.6
  package/oxide/package
Labels: packages

#733 Update KOReader to v2023.08
  package/koreader/package
Labels: packages

#734 Add note about toltecmk to docs/building.md
  docs/building.md
Labels: documentation
