Repository toltec-dev/toltec, pull requests merged in 2023-05, with the labels that each got.

#670 [rmkit] update rmkit, harmony, simple, remux and rpncalc
  package/rmkit/changelog
  package/rmkit/package
Labels: packages

#686 Don't enable rm2fb if it fails to start
  package/display/package
Labels: packages

#685 Update toltec-base to 1.2-1
  package/toltec-base/package
  scripts/install-lib
Labels: packages, tooling

#688 Update restream to 1.2
  package/restream/package
Labels: packages

#687 Update fbink, fbdepth, and fbink-doom to 1.25.0
  package/fbink/package
Labels: packages

#681 Update KOReader to v2023.04
  package/koreader/package
Labels: packages

#693 Stable merge for week 19 of 2023
  package/display/package
  package/fbink/package
  package/kernelctl/package
  package/koreader/package
  package/restream/package
  package/rmkit/changelog
  package/rmkit/package
  package/templatectl/package
  package/toltec-base/package
  scripts/install-lib
Labels: merge
