Repository toltec-dev/toltec, pull requests merged in 2024-06, with the labels that each got.

#704 Better bootstrap check-install
  package/toltec-bootstrap/package
  scripts/bootstrap/bootstrap
Labels: install

#789 Update the build process to use toltecmk
  .github/actions/setup/action.yml
  .gitignore
  Makefile
  requirements.txt
  scripts/build/__init__.py
  scripts/build/graphlib.py
  scripts/build/paths.py
  scripts/build/repo.py
  scripts/build/util.py
  scripts/install-lib
  scripts/package_build.py
  scripts/repo_build.py
  scripts/templates/listing.html
  scripts/toltec/bash.py
  scripts/toltec/builder.py
  scripts/toltec/ipk.py
  scripts/toltec/recipe.py
  scripts/toltec/templating.py
  scripts/toltec/util.py
  scripts/toltec/version.py
Labels: tooling

#879 allow open-remarkable-shutdown on rm1os3
  package/open-remarkable-shutdown/package
Labels: packages

#880 Split toltec-deletions rm1/rm2 for open-remarkable-shutdown
  package/toltec-deletions/package
Labels: bug, packages, experimental

#877 Stable merge for week 22 of 2014
  package/appmarkable/package
  package/micro/package
  package/open-remarkable-shutdown/package
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
  package/toltec-deletions/package
  package/webinterface-upload-button/package
  scripts/bootstrap/bootstrap
  scripts/toltec/builder.py
Labels: merge

#732 package/linux-mainline: Bump to 6.3
  package/linux-mainline/package
  package/toltec-deletions/package
Labels: packages

#882 Fix invalid launcherctl status output when using remux
  package/rmkit/launcherctl-remux
  package/rmkit/package
Labels: packages

#741 Don't overwrite other LD_PRELOAD env values
  package/display/package
  package/display/rm2fb-preload.env
Labels: packages

#833 Update oxide to v2.8.4
  package/display/package
  package/oxide/package
  package/sysfs_preload/package
  package/xochitl/package
  package/xochitl/xochitl.oxide
Labels: packages

#887 Workaround #886
  package/toltec-deletions/package
Labels: bug, packages, install
