Repository toltec-dev/toltec, pull requests merged in 2024-05, with the labels that each got.

#759 Add support for limiting packages to OS versions
  .github/actions/setup/action.yml
  .github/actions/sync-repository/action.yml
  .github/workflows/pr.yml
  docs/package.md
  package/Compatibility
  package/ddvk-hacks/package
  package/fuse/package
  package/kernelctl/package
  package/signature-rm/package
  package/templatectl/package
  package/toltec-base/package
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
  package/toltec-completion/_toltecctl
  package/toltec-completion/package
  package/toltec-deletions/package
  package/webinterface-onboot/package
  package/webinterface-upload-button/package
  package/wireguard/package
  requirements.txt
  scripts/bootstrap/bootstrap
  scripts/install-lib
  scripts/repo_build.py
  scripts/toltec/bash.py
  scripts/toltec/builder.py
  scripts/toltec/repo.py
Labels: packages, tooling, install, experimental

#843 Update package: neofetch
  package/neofetch/package
Labels: packages

#842 Add package: webinterface-localhost
  package/webinterface-localhost/package
  package/webinterface-localhost/webinterface-localhost.service
  package/webinterface-localhost/webinterface-localhost.socket
  requirements.txt
Labels: packages

#830 Stable merge for week 4 of 2024
  .github/workflows/pr-labels.yml
  .github/workflows/pr.yml
  .github/workflows/stable.yml
  .github/workflows/testing.yml
  Makefile
  package/folly/package
  package/koreader/package
  package/linux-stracciatella/package
  package/move-logs-to-opt/package
  package/move-logs-to-opt/var-log.mount
  package/oxide/package
  package/puzzles/package
  package/rm2-suspend-fix/package
  package/rmfakecloud-proxy/package
  package/rmfakecloud-proxy/rmfakecloudctl
  package/rmkit/changelog
  package/rmkit/package
  package/tilem/package
  package/toltec-base/package
  package/yaft/input.patch
  package/yaft/package
  package/zoneinfo-utils/package
Labels: merge

#838 Update KOReader to v2024.04
  package/koreader/package
Labels: packages

#829 Update display to v0.0.33
  package/display/package
Labels: packages

#800 Update netevent to 2.2.2
  package/netevent/package
Labels: packages

#718 Add support for rm-sync in xochitl package
  package/xochitl/manual-sync@.service
  package/xochitl/package
  package/xochitl/xochitl
  scripts/install-lib
Labels: packages

#713 Add zerotier-one
  package/zerotier-one/package
Labels: packages

#792 Add tool to handle entware services
  package/entware-rc/entware-rc@.service
  package/entware-rc/package
  package/entware-rc/rcctl
  package/toltec-base/package
  package/toltec-completion/_rcctl
  package/toltec-completion/package
Labels: packages

#849 Use systemctl to reboot
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
Labels: bug, packages

#861 Remove open-remarkable-shutdown from os3 due to it not working
  package/open-remarkable-shutdown/package
  package/toltec-deletions/package
Labels: packages

#864 Add missing dependencies for launcherctl scripts
  package/oxide/package
Labels: packages

#858 Stable merge for week 21 of 2024
  .github/actions/setup/action.yml
  .github/actions/sync-repository/action.yml
  .github/workflows/pr.yml
  docs/package.md
  package/Compatibility
  package/ddvk-hacks/package
  package/display/package
  package/draft/launcherctl-draft
  package/draft/package
  package/entware-rc/entware-rc@.service
  package/entware-rc/package
  package/entware-rc/rcctl
  package/fuse/package
  package/gocryptfs/package
  package/innernet/package
  package/kernelctl/package
  package/koreader/launcherctl-koreader
  package/koreader/package
  package/launcherctl/launcherctl
  package/launcherctl/package
  package/linux-mainline/package
  package/neofetch/package
  package/netevent/package
  package/open-remarkable-shutdown/package
  package/oxide/launcherctl-oxide
  package/oxide/package
  package/remarkable-stylus/package
  package/rmkit/launcherctl-remux
  package/rmkit/package
  package/signature-rm/package
  package/sudoku/package
  package/templatectl/package
  package/toltec-base/package
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
  package/toltec-completion/_launcherctl
  package/toltec-completion/_rcctl
  package/toltec-completion/_toltecctl
  package/toltec-completion/package
  package/toltec-deletions/package
  package/webinterface-localhost/package
  package/webinterface-localhost/webinterface-localhost.service
  package/webinterface-localhost/webinterface-localhost.socket
  package/webinterface-onboot/package
  package/webinterface-upload-button/package
  package/wireguard/package
  package/xochitl/launcherctl-xochitl
  package/xochitl/manual-sync@.service
  package/xochitl/package
  package/xochitl/xochitl
  package/zerotier-one/package
  requirements.txt
  scripts/bootstrap/bootstrap
  scripts/install-lib
  scripts/repo_build.py
  scripts/toltec/bash.py
  scripts/toltec/builder.py
  scripts/toltec/repo.py
Labels: merge

#863 Update issue templates to ask for toltecctl status output
  .github/ISSUE_TEMPLATE/installation-issue.md
  .github/ISSUE_TEMPLATE/package-issue.md
Labels: documentation, merge

#870 Fix sha256sum validation
  package/micro/package
  package/webinterface-upload-button/package
  scripts/toltec/builder.py
Labels: packages, tooling

#873 Fix upper case LOG in toltecctl
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
Labels: bug, packages, install

#690 Reload udev on uninstall of toltec-boostrap
  package/toltec-bootstrap/package
Labels: packages
