Repository toltec-dev/toltec, pull requests merged in 2024-01, with the labels that each got.

#816 package: webinterface-onboot depends on libbfd
  package/webinterface-onboot/package
Labels: packages

#812 Stable merge window for week 52 of 2023
  package/7zip/package
  package/bottom/package
  package/lf/package
  package/ripgrep/package
  package/webinterface-onboot/package
  package/webinterface-onboot/webinterface-onboot-toltec.service
  package/webinterface-upload-button/package
Labels: merge

#817 add sudoku
  package/sudoku/package
Labels: packages

#813 Update package: webinterface-onboot
  package/webinterface-onboot/package
Labels: packages

#808 Update linux-stracciatella to 5.4.70.4
  package/linux-stracciatella/package
Labels: packages

#819 Stable merge window for week 1 of 2024
  package/sudoku/package
  package/webinterface-onboot/package
Labels: merge

#823 Pin specific versions of Folly's clang deps
  package/folly/package
Labels: bug, packages

#806 toltec-base: Disable busybox-ifplugd@usb1.service
  package/toltec-base/package
Labels: packages

#702 Update zoneinfo-utils to 2023c
  .github/workflows/pr-labels.yml
  .github/workflows/pr.yml
  .github/workflows/stable.yml
  .github/workflows/testing.yml
  Makefile
  package/zoneinfo-utils/package
Labels: packages

#763 Update yaft to v0.1.1
  package/yaft/input.patch
  package/yaft/package
Labels: packages

#760 Update oxide to v2.7
  package/oxide/package
Labels: packages

#785 Update puzzles to 0.2.4
  package/puzzles/package
Labels: packages

#826 Update KOReader to v2024.01
  package/koreader/package
Labels: packages

#821 Add move-logs-to-opt
  package/move-logs-to-opt/package
  package/move-logs-to-opt/var-log.mount
  package/rm2-suspend-fix/package
Labels: packages

#825 [rmkit] update rmkit to latest (2024-01-11)
  package/rmkit/changelog
  package/rmkit/package
Labels: packages

#764 Update tilem to v0.1.1
  package/tilem/package
Labels: packages

#757 rmfakecloudctl: Don't error if there are no metadata files
  package/rmfakecloud-proxy/rmfakecloudctl
Labels: packages

#831 Update rmfakecloud-proxy version number
  package/rmfakecloud-proxy/package
Labels: packages
