Repository toltec-dev/toltec, pull requests merged in 2024-09, with the labels that each got.

#901 Stable merge for week 26 of 2024
  .github/actions/setup/action.yml
  .gitignore
  Makefile
  package/7zip/package
  package/bandwhich/package
  package/bottom/package
  package/display/package
  package/display/rm2fb-preload.env
  package/koreader/package
  package/lf/package
  package/oxide/package
  package/ripgrep/package
  package/rmkit/launcherctl-remux
  package/rmkit/package
  package/sysfs_preload/package
  package/toltec-base/opt-usr-bin.sh
  package/toltec-base/package
  package/toltec-bootstrap/package
  package/toltec-bootstrap/toltecctl
  package/toltec-deletions/package
  package/xochitl/package
  package/xochitl/xochitl.oxide
  requirements.txt
  scripts/build/__init__.py
  scripts/build/graphlib.py
  scripts/build/paths.py
  scripts/build/repo.py
  scripts/build/util.py
  scripts/install-lib
  scripts/package_build.py
  scripts/repo_build.py
  scripts/templates/listing.html
  scripts/toltec/bash.py
  scripts/toltec/builder.py
  scripts/toltec/ipk.py
  scripts/toltec/recipe.py
  scripts/toltec/templating.py
  scripts/toltec/util.py
  scripts/toltec/version.py
Labels: merge

#909 Fix #907
  package/signature-rm/package
  package/toltec-base/package
  package/toltec-deletions/package
  requirements.txt
Labels: bug, packages, tooling

#911 Hotfix: Fix incorrect dependencies for some packages
  package/signature-rm/package
  package/toltec-base/package
  package/toltec-deletions/package
  requirements.txt
Labels: merge

#905 Kernelctl os version
  package/kernelctl/kernelctl
  package/kernelctl/package
Labels: packages

#917 Update whiteboard-hypercard to 0.5.0
  package/whiteboard-hypercard/package
  package/whiteboard-hypercard/whiteboard-hypercard.draft
Labels: packages

#919 Bump toltec-deletions version as stable is out of sync
  package/toltec-deletions/package
Labels: bug, packages

#921 Fix builds
  package/linux-mainline/package
Labels: packages

#923 Fix sysfs_preload category
  package/sysfs_preload/package
Labels: bug, packages

#922 Fix launcherctl category
  package/launcherctl/package
Labels: bug, packages

#924 Add writing section as we have apps in it already
  docs/package.md
Labels: documentation

#878 Fix mmc-utils build
  package/mmc-utils/package
Labels: packages

#868 Update innernet-client to 1.6.1
  package/innernet/package
Labels: packages

#913 Update yaft and tilem to 0.1.2
  package/tilem/package
  package/yaft/package
Labels: packages

#918 Update zerotier-one to 1.14.1
  package/zerotier-one/package
Labels: packages

#914 Update micro to 2.0.14
  package/micro/package
Labels: packages

#916 Update koreader to 2024.07
  package/koreader/package
Labels: packages

#920 Stable merge for week 37 of 2024
  package/kernelctl/kernelctl
  package/kernelctl/package
  package/linux-mainline/package
  package/toltec-deletions/package
  package/whiteboard-hypercard/package
  package/whiteboard-hypercard/whiteboard-hypercard.draft
Labels: merge

#895 Update github actions to latest
  .github/actions/setup/action.yml
  .github/workflows/pr.yml
  .github/workflows/stable.yml
  .github/workflows/testing.yml
Labels: tooling
